cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('', views.cart_detail, name='cart_detail')
    
]

estore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from order import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('payment/', include('payment.urls')),
    path('callback/', views.webhook, name='callback'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path
from . import views

app_name='payment'

urlpatterns = [
    path('', views.payment_process, name='payment'),
    
    
]

payment/models.py
from django.db import models

# Create your models here.

payment/views.py
from asyncio import log
from django.http import HttpResponse
from django.shortcuts import redirect, render, get_object_or_404
from order.models import Order
from rave_python import Rave
import math
import random
import requests
import environ
import os
from django.views.decorators.http import require_POST
from django.views.decorators.csrf import csrf_exempt
# from rest_framework

# Create your views here.

env = environ.Env()
environ.Env.read_env()

rave = rave = (Rave(os.getenv('RAVE_PUBLIC_KEY'), os.getenv('RAVE_SECRET_KEY')))


def payment_process(request):
    order_id = request.session.get('order_id')
    order = get_object_or_404(Order,id=order_id)
    total_cost = order.get_total_price()
    auth_token = env('RAVE_SECRET_KEY')
    hed = {'Authorization': 'Bearer ' + auth_token}
    data = {
        'tx_ref':'' +str(math.floor(10000 +random.random() * 800000)),
        'amount':f'{total_cost}',
        'currency':'NGN',
        'redirect_url':'http://127.0.0.1:8000',
        'payment_options':'card',
        'customer':{
            'email':request.POST.get('email'),
            'phoneumber':request.POST.get('phone'),
            'name':request.POST.get('name')
        }
    }
    
    
    
    url = 'https://api.flutterwave.com/v3/payments'
    response = requests.post(url,json=data,headers=hed)
    response=response.json()
    link=response['data']['link']
    return redirect(link)


def webhook(request):
    secret_hash = env('secret_hash')
    signature = request.headers.get('verifi-hash')
    if signature == None or (signature != secret_hash):
        return HttpResponse(status=401)
    payload = request.body
    log(payload)
    return HttpResponse(status=200)

payment/templates/done.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>successful</title>
</head>
<body>
    
</body>
</html>

payment/templates/payment.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Payment point</title>
</head>
<body>
    <h1>Make Payment</h1>
    
</body>
</html>

payment/templates/process.html
{% extends 'base.html' %}
{% load static %}

{% block nav-content %}


    
{% endblock nav-content %}  


{% block payment %}
<section class="payment-section">
<div class="payment">
  <h1>Make Payments</h1>
<form action="{% url 'payment:payment' %}" method="post">
  {% csrf_token %}
  <div class="col-md-6 mb-3">
    <label for="cc-name">Name on card</label>
    <input type="text" class="form-control" id="cc-name" name="'Fname" placeholder="Firstname" required>

    <label for="cc-name">Name on card</label>
    <input type="text" class="form-control" id="cc-name" name="lname" placeholder="Lastname" required>

    <small class="text-muted">Full name as displayed on card</small>
    <div class="invalid-feedback">
      Name on card is required
    </div>
  </div>
  <h3>pays</h3>
  <div class="col-md-6 mb-3">
    <label for="cc-number">Credit card number</label>
    <input type="text" name="card-no" class="form-control" id="cc-number" placeholder="" required>
    <div class="invalid-feedback">
      Credit card number is required
    </div>
  </div>

  <div class="row">
    <div class="col-md-3 mb-3">
      <label for="cc-expiration">Month</label>
      <input type="text" class="form-control" id="cc-expiration" name="month" placeholder="08/39" required>

      <label for="cc-expiration">Year</label>
      <input type="text" class="form-control" id="cc-expiration" name="year" placeholder="08/39" required>

      <div class="invalid-feedback">
        Expiration date required
      </div>
    </div>
    <div class="col-md-3 mb-3">
      <label for="cc-expiration">CVV</label>
      <input type="text" name="cvv" class="form-control" id="cc-cvv" placeholder="" required>
      <div class="invalid-feedback">
        Security code required
      </div>
    </div>
  </div>

  <button type="submit">Make Payment</button>

</form>
</div>
</section>
{% endblock payment %}
  




{% block side-nav %}
  
{% endblock side-nav %}
  


  <script src="{% static 'js/flutterwave.js' %}"></script>
</body>
</html>