cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('', views.cart_detail, name='cart_detail')
    
]

estore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from order import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('payment/', include('payment.urls')),
    path('callback/', views.webhook, name='callback'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from . import views

app_name='order'

urlpatterns = [
    path('', views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    
    
    
]

order/models.py
from django.db import models
from store.models import Product

# Create your models here.

class Order(models.Model):
    first_name = models.CharField(max_length=10)
    last_name = models.CharField(max_length=10)
    phone = models.IntegerField()
    address = models.CharField(max_length=30)
    email = models.EmailField()
    paid = models.BooleanField(default=False)
    
    def __str__(self):
        return f'Order, {self.id}'
    
    def get_total_price(self):
        return sum(item.get_cost() for item in self.items.all())
    
    
class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name= 'order_item', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveBigIntegerField(default=1)
    
    
    def __str__(self):
        return str(self.id)
    
    
    def get_cost(self):       
        return self.price * self.quantity
    
    

order/forms.py
from pyexpat import model
from django import forms
from.models import Order


class OrderCreationForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'phone', 'address', 'email']
        

order/views.py
from django.http import HttpResponse
import environ
from django.urls import reverse
from django.contrib.admin.views.decorators import staff_member_required


from order.tasks import order_created
from.models import OrderItem, Order
from.forms import OrderCreationForm
from cart.cart import Cart
import requests
import math
import random
from django.shortcuts import HttpResponse, get_object_or_404, render, redirect
from rave_python import Rave, RaveExceptions, Misc
import os
from django.views.decorators.http import require_http_methods
from django.views.decorators.csrf import csrf_exempt
import json



env = environ.Env()
environ.Env.read_env()



'FLWSECK_TEST-0ab780a5f4b1a4f8bb3c6daaed89255b-X'

rave = (Rave(os.getenv('RAVE_PUBLIC_KEY'), os.getenv('RAVE_SECRET_KEY')))

# Create your views here.

def order_create(request):
    cart = Cart(request)
    if request.method =='POST':
        form = OrderCreationForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)            
            name = obj.first_name + '' + obj.last_name
            email = obj.email
            phonenumber = obj.phone
            
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order,
                                         product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity'],
                                        )
                
            cart.clear()
            #launch asynchronous task
            order_created.delay(order.id)  
            
            # save the order
            request.session['order_id'] = order.id
            order_id = request.session.get('order_id')
            order = get_object_or_404(Order,id=order_id)
            total_cost = order.get_total_price()
            auth_token = env('RAVE_SECRET_KEY')
            hed = {'Authorization': 'Bearer ' + auth_token}
            data = {
                'tx_ref':'' +str(math.floor(10000 +random.random() * 800000)),
                'amount':f'{total_cost}',
                'currency':'NGN',
                'redirect_url':'http://127.0.0.1:8000/callback',
                'payment_options':'card',
                'customer':{
                    'email':email,
                    'phoneumber':phonenumber,
                    'name':name
                }
            }
    
    
    
            url = 'https://api.flutterwave.com/v3/payments'
            response = requests.post(url,json=data,headers=hed)
            response=response.json()
            link=response['data']['link']
            response = requests.post('https://webhook.flutterwave.com/1l6lz5w1')
            print(response.status_code)
            
            
            
            return redirect(link)        
            
    
        
    else:
        form = OrderCreationForm()
    return render(request, 'order.html', {'form':form, 'cart':cart})


@csrf_exempt
@require_http_methods(['POST', 'GET'])
def webhook(request):
    order_id = request.session.get('order_id')
    order = get_object_or_404(Order,id=order_id)
    secret_hash = env('secret_hash')
    signature = request.headers.get('verifi-hash')
    status=request.GET.get('status', None)
    tx_ref=request.GET.get('tx_ref', None)
    
    
    if  status == 'successful':
        order.paid =True
        order.save()
        return HttpResponse(status=200)
    
    
    
    else:
        return HttpResponse('payment was cancelled')
    
    
    if signature == None or (signature != secret_hash):
        return HttpResponse(status=401)
    
    print(status)
    print(tx_ref)
    
    
@staff_member_required
def admin_order_detail(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    return render(request, 'admin/detail.html', {'order':order})
   
    
   
    
    

order/templates/order.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load humanize %}

{% block title %}
  order
{% endblock title %}
  
  <!--Main layout-->
  
  {% block nav-content %}
  <main class="mt-5 pt-4">
    <div class="container wow fadeIn">

      <!-- Heading -->
      <h2 class="my-5 h2 text-center">Checkout form</h2>

      <!--Grid row-->
      <div class="row">

        <!--Grid column-->
        <div class="col-md-8 mb-4">

          <!--Card-->
          <div class="card">

            <!--Card content-->
           <form action="{% url 'order:order_create' %}" method="post">
            {% csrf_token %}
               {{ form|crispy }}
               
              <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>

            
           </form>
           

          </div>
          <!--/.Card-->

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-4 mb-4">

          <!-- Heading -->
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Your cart</span>
            
            {% with cart_item=cart|length %}
            <span class="badge badge-secondary badge-pill">{{ cart_item }}</span>
            {% endwith %}
                
            
          </h4>

          <!-- Cart -->
          
          {% for item in cart %}

          {% with product=item.product %}
          <ul class="list-group mb-3 z-depth-1">
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">{{ product.name }}</h6>
              </div>
              <span class="text-muted">&#8358; {{ product.price | intcomma }}</span>
              <span class="text-muted"> {{ item.quantity }}</span>
            </li>
            <li class="list-group-item d-flex justify-content-between bg-light">
              <div class="text-success">
                <h6 class="my-0">Promo code</h6>
                <small>EXAMPLECODE</small>
              </div>
              <span class="text-success">&#8358; </span>
            </li>
            <li class="list-group-item d-flex justify-content-between">
              <span>Total (Naira)</span>
              <strong>&#8358;{{ item.total_cost |intcomma }}</strong>
            </li>
          </ul>

          {% endwith %}
              
          {% endfor %}
          <!-- Cart -->

          <!-- Promo code -->
          <form class="card p-2">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Promo code" aria-label="Recipient's username" aria-describedby="basic-addon2">
              <div class="input-group-append">
                <button class="btn btn-secondary btn-md waves-effect m-0" type="button">Redeem</button>
              </div>
            </div>
          </form>
          <!-- Promo code -->

        </div>
        <!--Grid column-->
              
         
              
          
          
              
          

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->

  <!--Footer-->
  <footer class="page-footer text-center font-small mt-4 wow fadeIn">

    <!--Call to action-->
    <div class="pt-4">
      <a class="btn btn-outline-white" href="https://mdbootstrap.com/docs/jquery/getting-started/download/" target="_blank" role="button">Download MDB
        <i class="fas fa-download ml-2"></i>
      </a>
      <a class="btn btn-outline-white" href="https://mdbootstrap.com/education/bootstrap/" target="_blank" role="button">Start free tutorial
        <i class="fas fa-graduation-cap ml-2"></i>
      </a>
    </div>
    <!--/.Call to action-->

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="https://www.facebook.com/mdbootstrap" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="https://twitter.com/MDBootstrap" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>

      <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
        <i class="fab fa-google-plus-g mr-3"></i>
      </a>

      <a href="https://dribbble.com/mdbootstrap" target="_blank">
        <i class="fab fa-dribbble mr-3"></i>
      </a>

      <a href="https://pinterest.com/mdbootstrap" target="_blank">
        <i class="fab fa-pinterest mr-3"></i>
      </a>

      <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>

      <a href="http://codepen.io/mdbootstrap/" target="_blank">
        <i class="fab fa-codepen mr-3"></i>
      </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2019 Copyright:
      <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> MDBootstrap.com </a>
    </div>
    <!--/.Copyright-->

  </footer>
  <!--/.Footer-->

  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="js/jquery-3.4.1.min.js"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="js/popper.min.js"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="js/bootstrap.min.js"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="js/mdb.min.js"></script>
  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();
  </script>
</body>

</html>

  {% endblock nav-content %}
      
  