cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('', views.cart_detail, name='cart_detail')
    
]

estore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from order import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('payment/', include('payment.urls')),
    path('callback/', views.webhook, name='callback'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('product/<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('category/<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('price/<slug:price_slug>/', views.product_list, name='product_price_filter'),
]

store/models.py
from django.forms import SlugField
from django.urls import reverse
from django.db import models


class Product_Tag(models.Model):
    product_tag = (
        ('best seller', 'best seller',
         'new', 'new',
         'old', 'old')
    )
    name = models.CharField(max_length=13)
    
    def __str__(self):
        return self.name
    
    

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=12, db_index=True)
    slug = models.SlugField(null=False, unique=True)
    image = models.ImageField(upload_to='media/category', blank=True, null=True)
    
    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'
        
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('store:product_list_by_category', args=[self.slug])
  
    
class Carousel(models.Model):
    name = models.CharField(max_length=13)
    image = models.ImageField(upload_to='media/banner')
    slug = models.SlugField(null=False, unique=True)
    
    def __str__(self):
        return self.name
    

class Price_filter(models.Model):
    price_filter = (
        ('100 - 1000', '100.00 - 1000'),
        ('1000 - 5000', '1000 - 5000'),
        ('5000 - 10000', '5000 - 10000'),
        ('10000 - 20000', '10000 - 20000'),
        ('20000 - 50000', '20000 - 50000'),
    )
    slug = models.SlugField(unique=True, null=False)
    price = models.CharField(choices=price_filter, max_length=13)
    
    def __str__(self):
        return self.price
    
    def get_absolute_url(self):
        return reverse("store:product_price_filter", args=[self.slug])
    

    
    
    
# create products
class Product(models.Model):
    name = models.CharField(max_length=20)
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    description = models.TextField(default='lets make a description right here. You cant get a better product than what we have here', null=True,
                                    blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    price_filter = models.ForeignKey(Price_filter, on_delete=models.CASCADE, blank=True, max_length=13)
    available = models.BooleanField(default=False)
    image = models.ImageField(upload_to='media/product')
    add_to_carousel = models.ForeignKey(Carousel, related_name='carousels', on_delete=models.CASCADE, null=True, blank=True)
    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now=True)
    slug = models.SlugField(unique=True, null=False)
    
    class Meta:
        ordering = ['-created']
        index_together = (('id', 'slug'),)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.id, self.slug])


    

store/views.py
from django.shortcuts import render, get_object_or_404
from.models import Product, Category, Carousel, Price_filter
from cart.forms import CartAddProductForm

# Create your views here.

def product_list(request, category_slug=None, price_slug=None):
    category = None
    price_filter = None
    prices = Price_filter.objects.all()
    carousels = Carousel.objects.all()
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    
    
    if price_slug:
        price_filter = get_object_or_404(Price_filter, slug=price_slug)
        products = products.filter(price_filter=price_filter)

    
    
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'index.html', {'categories':categories, 
                                                        'category':category,
                                                        'products':products,
                                                        'carousels':carousels,
                                                        'prices':prices,
                                                        'price_filter':price_filter,
                                                        }
                                                        )
    
def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'product.html', {'product':product, 'cart_product_form': cart_product_form})

store/templates/banner.html
<!-- Start Small Banner  -->
<section class="small-banner section">
    <div class="container-fluid">
        <div class="row">
            <!-- Single Banner  -->
            <div class="col-lg-12 col-md-6 col-12">
                
                <div class="single-banner">
                    <img src="https://via.placeholder.com/600x370" alt="#">
                    <div class="content">
                        <p>Man's Collectons</p>
                        <h3>Summer travel <br> collection</h3>
                        <a href="#">Discover Now</a>
                    </div>
                </div>
            </div>
            <!-- /End Single Banner  -->
            <!-- Single Banner  -->
            <div class="col-lg-4 col-md-6 col-12">
                <div class="single-banner">
                    <img src="https://via.placeholder.com/600x370" alt="#">
                    <div class="content">
                        <p>Bag Collectons</p>
                        <h3>Awesome Bag <br> 2020</h3>
                        <a href="#">Shop Now</a>
                    </div>
                </div>
            </div>
            <!-- /End Single Banner  -->
            <!-- Single Banner  -->
            <div class="col-lg-4 col-12">
                <div class="single-banner tab-height">
                    <img src="https://via.placeholder.com/600x370" alt="#">
                    <div class="content">
                        <p>Flash Sale</p>
                        <h3>Mid Season <br> Up to <span>40%</span> Off</h3>
                        <a href="#">Discover Now</a>
                    </div>
                </div>
            </div>
            <!-- /End Single Banner  -->
        </div>
    </div>
</section>
<!-- End Small Banner -->


<!-- Start Midium Banner  -->
<section class="midium-banner">
    <div class="container">
        <div class="row">
            <!-- Single Banner  -->
            <div class="col-lg-6 col-md-6 col-12">
                <div class="single-banner">
                    <img src="https://via.placeholder.com/600x370" alt="#">
                    <div class="content">
                        <p>Man's Collectons</p>
                        <h3>Man's items <br>Up to<span> 50%</span></h3>
                        <a href="#">Shop Now</a>
                    </div>
                </div>
            </div>
            <!-- /End Single Banner  -->
            <!-- Single Banner  -->
            <div class="col-lg-6 col-md-6 col-12">
                <div class="single-banner">
                    <img src="https://via.placeholder.com/600x370" alt="#">
                    <div class="content">
                        <p>shoes women</p>
                        <h3>mid season <br> up to <span>70%</span></h3>
                        <a href="#" class="btn">Shop Now</a>
                    </div>
                </div>
            </div>
            <!-- /End Single Banner  -->
        </div>
    </div>
</section>
<!-- End Midium Banner -->

store/templates/base.html
{% load static %}
{% load humanize %}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Estore|
    {% block title %}
        
    {% endblock title %}        
    </title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Bootstrap core CSS -->
	<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  	<link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  	<link href="{% static 'css/style.min.css' %}" rel="stylesheet">
	  <link rel="icon" type="image/png" href="{% static 'images/favicon.png' %}">
	<!-- Web Font -->
	<link href="https://fonts.googleapis.com/css?family=Poppins:200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&display=swap" rel="stylesheet">

    <script src="https://checkout.flutterwave.com/v3.js"></script>
	
	<!-- StyleSheet -->
	
	<!-- Bootstrap -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
	<!-- Magnific Popup -->
    <link rel="stylesheet" href="{% static 'css/magnific-popup.min.css' %}">
	<!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}">
	<!-- Fancybox -->
	<link rel="stylesheet" href="{% static 'css/jquery.fancybox.min.css' %}">
	<!-- Themify Icons -->
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
	<!-- Nice Select CSS -->
    <link rel="stylesheet" href="{% static 'css/niceselect.css' %}">
	<!-- Animate CSS -->
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
	<!-- Flex Slider CSS -->
    <link rel="stylesheet" href="{% static 'css/flex-slider.min.css' %}">
	<!-- Owl Carousel -->
    <link rel="stylesheet" href="{% static 'css/owl-carousel.css' %}">
	<!-- Slicknav -->
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}">
	
	<!-- Eshop StyleSheet -->
	<link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    
</head>
<body>
    {% include 'nav.html' %}
    {% block nav-content %}
	{% include 'carousel.html' %}
		
	{% endblock nav-content %}
	<div class="container-fluid">	
        
        {% block payment %}
            
        {% endblock payment %}
            
	
	
	

	
    {% block side-nav %}
    <div class="container">
        <div class="row mt-3 mr-3">
            
            <div class="col-3">
            {% include 'side-nav.html' %}
            </div>
            <div class="col-8">		
            {% block content %}
                
            {% endblock content %}
            </div>
        </div>
        </div>
        
    {% endblock side-nav %}
        
	
	
	
    
    </div>
{% include 'footer.html' %}	

				
	<!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>

  
  
  <!-- Jquery -->
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/jquery-migrate-3.0.0.js' %}"></script>
  <script src="{% static 'js/jquery-ui.min.js' %}"></script>
  <!-- Popper JS -->
  <script src="{% static 'js/popper.min.js' %}"></script>
  <!-- Bootstrap JS -->
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- Color JS -->
  <script src="{% static 'js/colors.js' %}"></script>
  <!-- Slicknav JS -->
  <script src="{% static 'js/slicknav.min.js' %}"></script>
  <!-- Owl Carousel JS -->
  <script src="{% static 'js/owl-carousel.js' %}"></script>
  <!-- Magnific Popup JS -->
  <script src="{% static 'js/magnific-popup.js' %}"></script>
  <!-- Fancybox JS -->
  <script src="{% static 'js/facnybox.min.js' %}"></script>
  <!-- Waypoints JS -->
  <script src="{% static 'js/waypoints.min.js' %}"></script>
  <!-- Countdown JS -->
  <script src="{% static 'js/finalcountdown.min.js' %}"></script>
  <!-- Nice Select JS -->
  <script src="{% static 'js/nicesellect.js' %}"></script>
  <!-- Ytplayer JS -->
  <script src="{% static 'js/ytplayer.min.js' %}"></script>
  <!-- Flex Slider JS -->
  <script src="{% static 'js/flex-slider.js' %}"></script>
  <!-- ScrollUp JS -->
  <script src="{% static 'js/scrollup.js' %}"></script>
  <!-- Onepage Nav JS -->
  <script src="{% static 'js/onepage-nav.min.js' %}"></script>
  <!-- Easing JS -->
  <script src="{% static 'js/easing.js' %}"></script>
  <!-- Active JS -->
  <script src="{% static 'js/active.js' %}"></script>
</body>
</html>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

store/templates/carousel.html
<div id="carouselExampleIndicators" class="carousel slide carousel-fade" data-bs-ride="carousel">
    <div class="carousel-indicators">
        
        {% for carousel in carousels %}
        
        {% if forloop.first %}
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="{{forloop.counter0 }}" class="active" ></button>

        {% else %}
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="{{forloop.counter0 }}"></button>

        {% endif %}           
          
        {% endfor %}
            
    </div>
    <div class="carousel-inner">
        
        {% for carousel in carousels %}
        
        {% if forloop.first %}
        <div class="carousel-item active">
            {% else %}
          <div class="carousel-item">            
        {% endif %}
        <img src="{{ carousel.image.url }}">  
        </div>
        {% endfor %}
          </div>
     
    </div>
    
  </div>

store/templates/footer.html
<!-- Start Footer Area -->
{% load static %}
<footer class="footer bg-black dark">
    <!-- Footer Top -->
    <div class="footer-top botom  section" style="height: 200;">
        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-md-6 col-12">
                    <!-- Single Widget -->
                    <div class="single-footer about">
                        <div class="logo">
                            <a href="index.html"><img src="{% static 'images/logo2.png' %}" alt="#"></a>
                        </div>
                        <p class="text">Praesent dapibus, neque id cursus ucibus, tortor neque egestas augue,
                              magna eros eu erat. Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, 
                              facilisis luctus, metus.</p>
                        <p class="call">Got Question? Call us 24/7<span><a href="tel:123456789">+234 456 789</a></span></p>
                    </div>
                    <!-- End Single Widget -->
                </div>
                <div class="col-lg-2 col-md-6 col-12">
                    <!-- Single Widget -->
                    <div class="single-footer links">
                        <h4>Information</h4>
                        <ul>
                            <li><a href="#">About Us</a></li>
                            <li><a href="#">Faq</a></li>
                            <li><a href="#">Terms & Conditions</a></li>
                            <li><a href="#">Contact Us</a></li>
                            <li><a href="#">Help</a></li>
                        </ul>
                    </div>
                    <!-- End Single Widget -->
                </div>
                <div class="col-lg-2 col-md-6 col-12">
                    <!-- Single Widget -->
                    <div class="single-footer links">
                        <h4>Customer Service</h4>
                        <ul>
                            <li><a href="#">Payment Methods</a></li>
                            <li><a href="#">Money-back</a></li>
                            <li><a href="#">Returns</a></li>
                            <li><a href="#">Shipping</a></li>
                            <li><a href="#">Privacy Policy</a></li>
                        </ul>
                    </div>
                    <!-- End Single Widget -->
                </div>
                <div class="col-lg-3 col-md-6 col-12">
                    <!-- Single Widget -->
                    <div class="single-footer social">
                        <h4>Get In Tuch</h4>
                        <!-- Single Widget -->
                        <div class="contact">
                            <ul>
                                <li>NO. 342 - Lagos Street.</li>
                                <li>Nigeria.</li>
                                <li>inf@mystore.com</li>
                                <li>+234 3456 7890</li>
                            </ul>
                        </div>
                        <!-- End Single Widget -->
                        <ul>
                            <li><a href="#"><i class="ti-facebook"></i></a></li>
                            <li><a href="#"><i class="ti-twitter"></i></a></li>
                            <li><a href="#"><i class="ti-flickr"></i></a></li>
                            <li><a href="#"><i class="ti-instagram"></i></a></li>
                        </ul>
                    </div>
                    <!-- End Single Widget -->
                </div>
            </div>
        </div>
    </div>
    <!-- End Footer Top -->
    <div class="copyright">
        <div class="container">
            <div class="inner">
                <div class="row">
                    <div class="col-lg-6 col-12">
                        <div class="left">
                            <p>Copyright © 2020 -  All Rights Reserved.</p>
                        </div>
                    </div>
                    <div class="col-lg-6 col-12">
                        <div class="right">
                            <img src="{% static 'images/payments.png' %}" alt="#">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- /End Footer Area -->

store/templates/index.html
{% extends 'base.html' %}
{% load humanize %}
{% block title %}
{% if category %}
{{ category.name }}
{% else %}
Products  
{% endif %}
  
{% endblock title %}
{% block content %}
    <div class="row">
     
    <h6>
    {% if category %}Category: {{ category.name }}
    
    {% elif price_filter %}Price:{{ price_filter.price}}
    
    {% else %}Category: All   
    {% endif %}
    
      
    </h6>
    {% for product in products %}
    <div class="card mb-3 mr-3 " style="width: 13rem;" >
      <a href="{{ product.get_absolute_url }}"><img src="{{ product.image.url }}" class="card-img-top" alt="..."></a>  
      <div class="card-body">
        

        <a href=""><span class="badge badge-pill danger-color">{{ product.category }}</span></a>
        <h6 class="card-title">{{ product.name }} </h6>
        
        <h3 class="card-text"><b>&#8358;{{ product.price | intcomma }} </b> </h3>
        <a href="{{ product.get_absolute_url }}" class="btn bg-info btn-sm" ><p> Add cart</p></a>
             
        
      
      </div>
    </div>    
    {% endfor %}
  </div>     
  
  {% include 'banner.html' %}
      

{% endblock content %}
 

store/templates/nav.html
<!-- Navbar -->
{% load humanize %}


<nav class="navbar fixed-top navbar-expand-lg navbar-dark dark bg-warning top-banner">
  <div class="container">
    <!-- Brand -->
    <a class="navbar-brand waves-effect" href="{% url 'store:product_list' %}" target="_blank">
      <strong class="white-text">ESTORE</strong>
    </a>

    <!-- Collapse -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Links -->  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <!-- Left -->
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link waves-effect" href="#">
            <span class="sr-only">(current)</span>
          </a>
        </li>       
      </ul>

      <!-- Right -->
      <ul class="navbar-nav nav-flex-icons">
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'cart:cart_detail' %}">
            <span class="badge red z-depth-1 mr-1">
              
              {% with cart_item=cart|length %}
              
              {% if cart_item > 0 %}

              <span class="clearfix d-none d-sm-inline-block">{{ cart_item}} Cart {{ cart_item | pluralize}}</span>

              {% else %}
              0
                
              {% endif %}                
                
              {% endwith %}                
              
            </span>
            <i class="fas fa-shopping-cart"></i>
             &#8358;{{ cart.get_total_price | intcomma }}
            
          </a>
        </li>
      </ul>

    </div>

  </div>
</nav>

<!-- Navbar -->

store/templates/product.html
{% extends 'base.html' %}
{% load humanize %}


{% block title %}
{{ product.name }}
  
{% endblock title %}
  

    



{% block nav-content %}
<!--Main layout-->

{% endblock nav-content %}


{% block content %}

<main class="mt-5 pt-4">
  <div class="container dark-grey-text mt-5">

    <!--Grid row-->
    <div class="row wow fadeIn">

      <!--Grid column-->
      <div class="col-md-6 mb-4">

        <img src="{{ product.image.url }}" class="img-fluid" alt="">

      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-md-6 mb-4">

        <!--Content-->
        <div class="p-4">

          <div class="mb-3">
            <a href="">
              <span class="badge purple mr-1">{{ product.category.name }}</span>
            </a>
            <a href="">
              <span class="badge blue mr-1">New</span>
            </a>
            <a href="">
              <span class="badge red mr-1">Bestseller</span>
            </a>
          </div>

          <p class="lead">
            <span>&#8358;{{ product.price | intcomma}}</span>
          </p>

          <p class="lead font-weight-bold">Description</p>

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Et dolor suscipit libero eos atque quia ipsa
            sint voluptatibus!
            Beatae sit assumenda asperiores iure at maxime atque repellendus maiores quia sapiente.</p>

          <form class="d-flex justify-content-left" action="{% url 'cart:cart_add' product.id %}" method="post">
            {{ cart_product_form }}
            {% csrf_token %}
            
            <button class="btn btn-primary btn-md my-0 p" type="submit">Add to cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </button>

          </form>

        </div>
        <!--Content-->

      </div>
      <!--Grid column-->

    </div>
    <!--Grid row-->

    <hr>

    <!--Grid row-->
    <div class="row d-flex justify-content-center wow fadeIn">

      <!--Grid column-->
      <div class="col-md-6 text-center">

        <h4 class="my-4 h4">Recommended Items</h4>

        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
          voluptates,
          quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

      </div>
      <!--Grid column-->

    </div>
    <!--Grid row-->

    <!--Grid row-->
    <div class="row wow fadeIn">

      <!--Grid column-->
      <div class="col-lg-4 col-md-12 mb-4">

        <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">

      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-4 col-md-6 mb-4">

        <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">

      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-4 col-md-6 mb-4">

        <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">

      </div>
      <!--Grid column-->

    </div>
    <!--Grid row-->

  </div>
</main>
<!--Main layout-->

  
{% endblock content %}
  

store/templates/side-nav.html
<h6>Categories</h6>
<div class="d-flex align-items-start m-3" width:20rem;>
    <div class="nav flex-column nav-pills me-3" id="v-pills-tab" role="tablist" aria-orientation="vertical">
        
        {% if not category %}    
        {% endif %}
        <a href="{% url 'store:product_list' %}" class="nav-link {% if request.path == product_url %} active {% endif %}" >All</a>
      
      {% for c in categories %}
      {% if category.slug == c.slug %} 
      {% endif %}
      
      <a href="{{ c.get_absolute_url }}" class="nav-link {% if request.path == c.get_absolute_url %} active bg-warning  {% endif %}">{{ c.name }}</a>
             
      {% endfor %}
        
      

    </div>
  </div>

  <h6> Price</h6>
  <div class="d-flex align-items-start m-3">
    <div class="nav flex-column nav-pills me-3" id="v-pills-tab" role="tablist" aria-orientation="vertical">       
      
      {% for p in prices %}
      
      {% if price_slug == p.slug %}
        
      {% endif %}
        
      
      <a href="{{ p.get_absolute_url }}" class="nav-link {% if request.path == p.get_absolute_url %} active bg-warning {% endif %}">{{ p.price }}</a>
             
      {% endfor %}

    </div>
  </div>

    
   

store/templates/tab-nav.html
<div class="container">
<div class="nav-main mt-3">
    
    <!-- Tab Nav -->
    <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#man" role="tab">Man</a></li>
        <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#women" role="tab">Woman</a></li>
        <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#kids" role="tab">Kids</a></li>
        <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#accessories" role="tab">Electronics</a></li>
        <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#essential" role="tab">Essential</a></li>
        <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#prices" role="tab">Prices</a></li>
    </ul>
    <!--/ End Tab Nav -->
</div>
</div>